FROM ubuntu:24.04

LABEL maintainer="K Syed Mohamed Hyder<syedhyder1362k@gmail.com>"

ARG proxy

ENV http_proxy=$proxy
ENV https_proxy=$proxy
ENV HTTP_PROXY=$proxy
ENV HTTPS_PROXY=$proxy
ENV ANSIBLE_CONFIG=/home/ansible/ansible.cfg

RUN apt-get update && apt-get install -y \
    software-properties-common \
    && apt-get clean

RUN apt-get update && apt-get install -y \
    openssh-server \
    openssh-client \
    ansible \
    && apt-get clean

RUN useradd -u 5000 -ms /bin/bash ansible

USER ansible

RUN mkdir -p /home/ansible/.ssh && \
    chmod 700 /home/ansible/.ssh

WORKDIR /home/ansible

RUN cp -r /etc/ansible/* /home/ansible/

EXPOSE 22

ENTRYPOINT ["ansible"]
