---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-home
  labels:
    app.kubernetes.io/name: ansible-home-pvc
    app.kubernetes.io/component: ansible-home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath
