---

apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: target
    app.kubernetes.io/name: ansible-target-centos
  name: ansible-target-centos
spec:
  type: ClusterIP
  ports:
  - port: 22
    protocol: TCP
    targetPort: ssh
  selector:
    app.kubernetes.io/component: target
    app.kubernetes.io/name: ansible-target-centos
