---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ansible-shared
  labels:
    app.kubernetes.io/name: ansible-shared-pv
    app.kubernetes.io/component: ansible-shared
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: 
  storageClassName: manual
