---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-workplace
  labels:
    app.kubernetes.io/name: ansible-workplace-pvc
    app.kubernetes.io/component: ansible-workplace
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ansible-workplace-pv
      app.kubernetes.io/component: ansible-workplace
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
