---

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "ansible.fullname" . }}
  labels:
    {{- include "ansible.labels" . | nindent 4 }}
    app.kubernetes.io/component: ssh-keys-generator
spec:
  completions: {{ .Values.job.completions }}
  parallelism: {{ .Values.job.parallelism }}
  backoffLimit: {{ .Values.job.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "ansible.labels" . | nindent 8 }}
        app.kubernetes.io/component: ssh-keys-generator
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      containers:
      - name: ssh-keys-generator
        image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag }}"
        command:
        - /bin/bash
        - -c
        - |
          echo "Username: $(whoami)"
          echo "UID: $(id -u)"
          mkdir -p {{ .Values.controller.home }}/.ssh/
          ssh-keygen -q -t rsa -N '' -f {{ .Values.controller.home }}/.ssh/id_rsa <<<y >/dev/null 2>&1
          echo "Successfully generated the ssh keys"
          cp {{ .Values.controller.home }}/.ssh/id_rsa.pub {{ .Values.controller.home }}/.ssh/authorized_keys
          chown -R {{ .Values.controller.securityContext.runAsUser }}:{{ .Values.controller.securityContext.runAsGroup }} {{ .Values.controller.home }}/.ssh
          chmod -R 700 {{ .Values.controller.home }}/.ssh
          echo "Updated the permissions of .ssh"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: ansible-home
          mountPath: {{ .Values.controller.home }}
      volumes:
      - name: ansible-home
        persistentVolumeClaim:
          claimName: {{ include "ansible.sharedTargetHome.pvc" . }}
