---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ansible.shared.pvc" . }}
  labels:
    {{- include "ansible.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "ansible.shared" . }}
spec:
  accessModes:
    {{- toYaml .Values.ansibleShared.accessModes | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.ansibleShared.capacity.storage | default "1Gi" }}
  selector:
    matchLabels:
      {{- include "ansible.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "ansible.shared" . }}
  storageClassName: {{ .Values.ansibleShared.storageClassName | default "manual" }}
