{{- range .Values.targets }}
---

apiVersion: v1
kind: Service
metadata:
  name: "{{ include "ansible.fullname" $ }}-{{ include "ansible.target.name" . }}"
  labels:
    {{- include "ansible.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ include "ansible.target.name" . }}
spec:
  type: ClusterIP
  ports:
  - port: 22
    protocol: TCP
    targetPort: ssh
  selector:
    {{- include "ansible.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ include "ansible.target.name" . }}
{{- end }}
