---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "ansible.workplace.pv" . }}
  labels:
    {{- include "ansible.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "ansible.workplace" . }}
spec:
  accessModes:
    {{- toYaml .Values.workplace.accessModes | nindent 2 }}
  capacity:
    storage: {{ .Values.workplace.capacity.storage | default "1Gi" }}
  hostPath:
    path: {{ .Values.workplace.hostPath.path }}
  storageClassName: {{ .Values.workplace.storageClassName | default "manual" }}
