FROM python:3.10.13-alpine

LABEL maintainer="K Syed Mohamed Hyder<syedhyder1362k@gmail.com>"

ARG proxy

ENV http_proxy=$proxy
ENV https_proxy=$proxy
ENV HTTP_PROXY=$proxy
ENV HTTPS_PROXY=$proxy
ENV ANSIBLE_CONFIG=/home/ansible/ansible.cfg

RUN pip install ansible

RUN adduser -u 5000 -D -s /bin/ash ansible \
    && chown -R ansible:ansible /home/ansible

USER ansible

WORKDIR /home/ansible

RUN ansible-config init --disabled > /home/ansible/ansible.cfg

ENTRYPOINT ["ansible-playbook"]
